apiVersion: batch/v1
kind: Job
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  parallelism: 10
  template:
    metadata:
      labels:
        name: consumer
    spec:
      containers:
      - name: consumer
        image: gcr.io/kubernetes-screen-173105/pipeline
        imagePullPolicy: Always
        env:
        - name: NODETYPE
          value: consumer
        - name: PROJECT_ID
          value: kubernetes-screen-173105
        - name: BQ_DATASET
          value: database
        - name: BQ_TABLE
          value: values
      restartPolicy: OnFailure
