apiVersion: batch/v1
kind: Job
metadata:
  name: producer
  labels:
    name: producer
spec:
  template:
    metadata:
      labels:
        name: producer
    spec:
      containers:
      - name: producer
        image: gcr.io/kubernetes-screen-173105/pipeline:v9
        env:
        - name: NODETYPE
          value: producer
        - name: REDISLIST
          value: redis-list
      restartPolicy: OnFailure